### ISSUE TITLE
Trying to run graphcast with the following command:  ai-models --input cds --date 20231001 --time 0000 graphcast  

### ISSUE THREAD

**Issue by tbwcy** [ecmwf-lab/ai-models-graphcast#12]
but I get the following error:
Traceback (most recent call last):
  File "/home/wcy/anaconda3/envs/largecpu/bin/ai-models", line 8, in <module>
    sys.exit(main())
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/ai_models/__main__.py", line 322, in main
    _main(sys.argv[1:])
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/ai_models/__main__.py", line 270, in _main
    run(vars(args), unknownargs)
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/ai_models/__main__.py", line 274, in run
    model = load_model(cfg["model"], **cfg, model_args=model_args)
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/ai_models/model.py", line 480, in load_model
    return available_models()[name].load()(**kwargs)
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/entrypoints.py", line 79, in load
    mod = import_module(self.module_name)
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/ai_models_graphcast/model.py", line 27, in <module>
    import haiku as hk
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/haiku/__init__.py", line 20, in <module>
    from haiku import experimental
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/haiku/experimental/__init__.py", line 34, in <module>
    from haiku._src.dot import abstract_to_dot
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/haiku/_src/dot.py", line 163, in <module>
    @jax.linear_util.transformation
  File "/home/wcy/anaconda3/envs/largecpu/lib/python3.10/site-packages/jax/_src/deprecations.py", line 54, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax' has no attribute 'linear_util'

**Comment by BluesCrossing** [comment]
Upgrade dm-haiku using `pip install dm-haiku==0.0.14` would help.
